# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteConfigsSampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemoteConfigsSampleProject
	pod 'Firebase/RemoteConfig'


  target 'RemoteConfigsSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteConfigsSampleProjectUITests' do
    # Pods for testing
  end

end
